# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check code format with black
      run: |
        black --fast --check  -l 100 pyintradel tests *.py

    - name: Lint with flake8
      run: |
        flake8 --max-line-length 100 pyintradel tests
      if: ${{ always() }}

    - name: Type check with mypy
      run: |
        mypy --strict pyintradel tests
      if: ${{ always() }}

    - name: Check new pypi version is correct
      run:
        (chmod +x .github/check_version.sh && sh .github/check_version.sh)
      if: ${{ always() }}